### ISSUE TITLE
Starting point index of each section

### ISSUE THREAD

**Issue by WeinaJi** [BlueBrain/MorphIO#116]
Hello, 

Currently I am trying to inject the morphology objects from MorphIO API into our package SpatialIndex. The SpatialIndex API has a method to add branches with an array of points (start/end points of segments), an array of radii, and an array of the first point index of each branch. For the first two arrays, I can use the property accessors of the MorphIO API (like Morphology.points, Morphology.diameters).
My question is that is it possible to get the index of the starting points of each section directly from the API? I am trying to avoid loops in Python for performance issue, so it would be better to have such array directly constructed by the API.

Suggestions and discussions are appreciated. 

Cheers,
Weina

**Comment by wizmer** [comment]
Hi,

Yes, I can add this as an attribute of the Morphology class. That will be a vector of int and each one will give you the offset in the point array. It will be available as `section_indices`. Sections will be in the depth first search order in a given neurite and the neurite order is the one of the file.

One thing to note is that Morphology.points only provides points belonging to neurites. Soma points can only be retrieved as `Morphology.soma.points`.

Does this sound good to you ?

**Comment by WeinaJi** [comment]
Hello Benoit, 

The ```section_indices``` sounds very good. Thanks !

Yes, I see that soma points are not included in the Morphology.points. In SpatialIndex we can add soma and segments separately per gid. Are the ```Morphology.points``` always connected to the first element of the array ```Morphology.soma.points``` ?

**Comment by wizmer** [comment]
No, the neurite point are not necessarily connected to the soma points. It may be, but it does not have to be.
