### ISSUE TITLE
Why providing default deleter when creating shared_ptr?

### ISSUE THREAD

**Issue by tristan0x** [BlueBrain/MorphIO#121]
While reading some code in MorphIO, I am wondering why some `shared_ptr` are constructed with a _deleter_ object calling `::delete` which is already the default behavior:

https://github.com/BlueBrain/MorphIO/blob/98ab539fb1b1ab915683997f7c3296dc6a3daaba/src/mut/mitochondria.cpp#L9-L18

Is there something that prevent using `std::make_shared`?
```c++
const auto ptr = std::make_shared<MitoSection>(this, _counter, section_);
```

**Comment by mgeplf** [comment]
Good eye, and good question - I can't really answer; this will probably have to wait until @wizmer is back.  I think the code needs a good going over for stuff like this, so if you notice other patterns that could be fixed, please open other tickets.

**Comment by tristan0x** [comment]
> so if you notice other patterns that could be fixed, please open other tickets.

I am working on a branch with similar changes. I will open a PR when @wizmer is back.

**Comment by tristan0x** [comment]
The _deleter_ functor given to `shared_ptr` constructor is usually used when the destructor of the class is private. In the current situation the constructors are private, and the destructor public. So IMO the _deleter_ functor is not required.

**Comment by mgeplf** [comment]
that explains that mystery: https://github.com/BlueBrain/MorphIO/blob/master/include/morphio/mut/section.h#L108

I guess it was `private` at some point.
