### ISSUE TITLE
Writing an h5 results in seg-fault if annotations are present on morphology

### ISSUE THREAD

**Issue by lidakanari** [BlueBrain/MorphIO#127]
Example (swc works but annotations are not written to file, h5 throws seg-fault error)
```
import morphio
m = morphio.mut.Morphology()
m.annotations.append('{"Apical point": (0, 1, 0)}')

m.write('Test annot.swc')
Warning: writing file without a soma

m.write('Test annot.h5')
Warning: writing file without a soma
Segmentation fault
```

**Comment by wizmer** [comment]
Annotations are not designed to be writable, it's a read-only object.
They just contain details about what happened when the files was opened (like single children, duplicates...).
And the segfault comes from the fact you are trying to write an empty morphology.

**Comment by tristan0x** [comment]
> And the segfault comes from the fact you are trying to write an empty morphology.

IMHO the library should not punish the user with a segfault.

**Comment by wizmer** [comment]
> IMHO the library should not punish the user with a segfault.
Yep. This has been fixed.
