### ISSUE TITLE
Set single value in mutable section

### ISSUE THREAD

**Issue by eleftherioszisis** [BlueBrain/MorphIO#129]
Allow to mutate the values of the section data without copying and rewriting the entire datasets every time we want to change a single value.

The most basic example would be like this (location in the vector followed by value):
```python
section.set_diameter(5, 0.1)
section.set_point(0, [0.1, 0.2, 0.3])
section.set_perimeter(2, 2.0)
```

**Comment by wizmer** [comment]
Since #137, properties are now mutable directly (even numpy indexing works)
```
section.points[2] = [0, 0, 0]
```
Numpy indexing, to change points at index 2 and 11:
```
section.points[[2, 11]] = [1, 1, 1]
```
