### ISSUE TITLE
Use C++14

### ISSUE THREAD

**Issue by tristan0x** [BlueBrain/MorphIO#133]
Is this normal that the tests use C++14 but the library C++11 ?

```
src/CMakeLists.txt:  CXX_STANDARD 11
src/CMakeLists.txt:  CXX_STANDARD_REQUIRED YES
tests/CMakeLists.txt:  CXX_STANDARD 14
tests/CMakeLists.txt:  CXX_STANDARD_REQUIRED YES
```

According to the TravisCI configuration, the oldest supported compiler seems to be GCC 5.4.0, in  Ubuntu xenial. This compiler version supports C++14, see [compatibility table](https://gcc.gnu.org/projects/cxx-status.html#cxx14)

So I don't see a reason not to switch to 14 and embrace `make_unique`, polymorphic lambda expressions, variable template, and much more.

Besides, full support to 17 on BB5 is on its way \o/

**Comment by wizmer** [comment]
The first MorphIO version used to use C++ 14 and in particular through its dependency https://github.com/Microsoft/GSL but during the open-source review it was decided to support C++ 11. 
@jdcourcol Is the C++ 11 compatibility still required ?
The tests using C++ 14 is probably a mistake.

**Comment by jdcourcol** [comment]
I think it is not clearly specified here: https://bbpteam.epfl.ch/project/spaces/display/BSD/Software+Deployment+Strategy+and+Support

**Comment by jdcourcol** [comment]
decision is to use C++14.

**Comment by mgeplf** [comment]
The decision was that `C++14` was fine in the BSD meeting.

I'd like to move the whole project to `C++14`; but I want some feedback from the users if that's ok.  Does anyone thumbs down this?

cc: @matz-e, @alexsavulescu, @jdcourcol, @chevtche, @NadirRoGue, @tristan0x, @alkino, @wvangeit, @tomdele (cc list created from https://github.com/BlueBrain/MorphIO/issues/235, if anyone else should be tagged, please do so)

**Comment by tristan0x** [comment]
> The decision was that `C++14` was fine in the BSD meeting.
> 
> I'd like to move the whole project to `C++14`; but I want some feedback from the users if that's ok. Does anyone thumbs down this?
> 
> cc: @matz-e, @alexsavulescu, @jdcourcol, @chevtche, @NadirRoGue, @tristan0x, @alkino, @wvangeit, @tomdele (cc list created from #235, if anyone else should be tagged, please do so)

I don't know much about MorphIO's community requirements, but BBP and HPC sites where we deploy our software stack support C++17. Besides, GCC shipped with Ubuntu LTS versions supports C++17 (>= GCC 7.4).

**Comment by alexsavulescu** [comment]
🚀  Just one flag to raise, `manylinux1` doesn't provide proper C++14 support.

**Comment by mgeplf** [comment]
> I don't know much about MorphIO's community requirements, 

Yup, I'm hoping that there won't be a blocking requirement from the community, but I just want to check.

> Just one flag to raise, manylinux1 doesn't provide proper C++14 support

Yup, we're already using manylinux2014, so that shouldn't be an issue: https://github.com/BlueBrain/MorphIO/blob/master/.github/workflows/publish-sdist-wheels.yml#L9

**Comment by mgeplf** [comment]
Ok, haven't heard any complaints for `C++14`, so I will be adding it.

Thanks for the feedback.
