### ISSUE TITLE
Setting a section property array (like point or diameter) changes its address

### ISSUE THREAD

**Issue by eleftherioszisis** [BlueBrain/MorphIO#139]
The latest morphio version has section properties to not return a copy in order to allow for single property setting.

However, this has the drawback that an initial local variable with the values is deallocating its memory before the end of the function scope if new values are set.

Any function that uses morphio and expects the getter to return values that persist until the end of the scope or change wrt to the new values, will lead to numerical errors.

I am afraid that this feature could possibly silently break tools that rely on morphio. If it weren't for my tests failing I wouldn't have realized this is taking place.

Example:
``` python
m = morphio.mut.Morphology(...)
s = m.sections[0]
a = s.points
a_copy = np.copy(a)
s.points = np.random.random((len(s.points, 3))
b = s.points

assert np.allclose(a, a_copy)
assert np.allclose(a, b)

```
I would expect that the second assertion should not fail.

**Comment by wizmer** [comment]
Yeah, I see what you mean. Please not that this behavior is not new. I'll see what I can do.

**Comment by eleftherioszisis** [comment]
Thanks for properly renaming the issue.

While the general behaviour is not new, in previous versions `s.points` returned a copy, therefore it didn't cause any issue on the user-side. Now it neither points to the old nor the new data.
