### ISSUE TITLE
Re-using existing build directories leads to hard to debug failures

### ISSUE THREAD

**Issue by matz-e** [BlueBrain/MorphIO#146]
We currently default to a "standard" build directory for the Python C++ extension:

https://github.com/BlueBrain/MorphIO/blob/cb69cbfa377528bf0e155415ced9d001e79a55cd/setup.py#L78

When building repeatedly, and changing the environment while doing so, re-using the default `build` directory can lead to outdated CMake caches and wrong builds. We should make sure that we either build in a temporary directory or clean the build directory before building ourselves. I'm in favor of the former. @mgeplf, opinions?

**Comment by mgeplf** [comment]
Hmm, interesting.  I think `self.build_temp` is meant to be constant, so that `python setup.py clean` can clean up build objects.  In your repeated building, does that command clean up enough to move forward?

**Comment by matz-e** [comment]
> Hmm, interesting. I think `self.build_temp` is meant to be constant, so that `python setup.py clean` can clean up build objects. In your repeated building, does that command clean up enough to move forward?

That would be fine if `self.build_temp` would not default to `build`, which is also the canonical default for building things with CMake, where the default workflow is `mkdir build; cd build; cmake ..`…

Forgetting that and switching to `setup.py` later on also leads to "funny" behavior. I'm not really a fan of unconditionally building in a directory that may have existed beforehand.

**Comment by mgeplf** [comment]
> That would be fine if self.build_temp would not default to build, which is also the canonical default for building things with CMake, where the default workflow is mkdir build; cd build; cmake ..…

It builds in a subdirectory of `build`, no? So I'm surprised it interacts with the CMake convention.
Keeping the default mechanism & behavior means that there is a consistency between how this package works, and how other python extension building packages works.  There is value in this, and changing it requires more than 'people's default habits are "mkdir build; ...."' in my opinion.

Note that you can also do: `python setup.py build_ext  -t $SOME_OTHER_DIR`

**Comment by matz-e** [comment]
You're right, it's in a subdirectory. Still, it's easy to re-use a stale build/CMake cache… I for one did not know about `setup.py clean`, and would take the cost of a fresh build over the hazard of using old settings.

**Comment by wizmer** [comment]
I tried to see if I could change `self.build_temp` but I did not manage to get `python setup.py clean` work with the new `self.build_temp`. @matz-e If you are happy with the Mike's proposal of running `python setup.py clean` before your builds, I'll close this.

**Comment by matz-e** [comment]
It's an easy thing to forget, I personally just nuke all `spack-*` and `build*` directories by now if things look fishy. I think it would be more user friendly if we could get this fixed properly…

**Comment by mgeplf** [comment]
>  this fixed properly…

I'm not sure what that means; the `setup.py` default has been `build` for a long time, so it seems like that would be something you'd have to take up with upstream.

I don't think we can work around people's cmake habits, nor do I really understand how this impacts them: as noted, the `setup.py` builds things in a subdirectory, so it's not even being touched by `cmake`.

**Comment by matz-e** [comment]
I just love how Python things build…

Using `python setup.py build` re-uses the same temp directory, `pip install .` uses a build directory in `/tmp`. I guess there's no real solution…

**Comment by mgeplf** [comment]
> Using python setup.py build re-uses the same temp directory,

AFAIK, that's done on purpose, so that you can develop your extensions and rely on your build system to do incremental builds.  Just like `Makefiles` - to clean, you use `clean`

pip is a different use case; it's a package installer.
