### ISSUE TITLE
Absorbing of single child sections

### ISSUE THREAD

**Issue by asanin-epfl** [BlueBrain/MorphIO#176]
Hello! I want to propose an update to API. Currently when MorphIO merges single child section into parent, user receives only a print warning message of WARNING_ONLY_CHILD. Shouldn't user receive en exception with the section being deleted and its parent section that absorbs it? Or provide a mapping between deleted sections and their new sections?

**Comment by asanin-epfl** [comment]
I see now there are some `annotations`. Can it be done via them?

**Comment by asanin-epfl** [comment]
Also lets look at this morphology. The section 5-6 will be merged with the section 4-5. My question shouldn't this merge happen only when the section 5-6 is a continuation of the section 4-5? I mean that they both make a single line. It seems logical for them to be different sections as they form an angle and emphasize the fact that morphology bends there.
![morph](https://developer.humanbrainproject.eu/docs/projects/morphology-documentation/0.0.2/_images/ExMorph.svg)

**Comment by eleftherioszisis** [comment]
A section is a chain, the vertices of which have a degree which exactly 2 apart from their start and end vertices that are either forks (degree > 2) or terminations (degree = 1). It's not a geometric classification of the tree, but a topological one. Having consecutive non-branching sections will break most tools that rely on this topological convention / definition.

Morphologies using the section representation should either not have them or should be curated to a valid structural representation. However, a mapping of the collapsing in the morphologies that do have that issue would be useful indeed.

**Comment by wizmer** [comment]
As discussed in the past (there is a ticket from you @eleftherioszisis somewhere about this but I can't find it), I will provide a mapper in morph-tool but not from section ID to section ID but from coordinate to section ID. This way, it is much more generic and can be used in multiple use cases.

**Comment by asanin-epfl** [comment]
As agreed at the meeting this won't solve simplification problems because there are morphologies directly from NEURON simulator and it won't help much to reindexing because it does not take too much code to implement it there.
