### ISSUE TITLE
Resampling function

### ISSUE THREAD

**Issue by marwan-abdellah** [BlueBrain/MorphIO#191]
I would like to request a new feature to be implemented and executed during the loading of vascular morphology. This function resamples each section in the morphology to remove unwanted or unnecessary samples. The implementation in C++ would be much faster than python and would save substantial amount of time whe loading large scale morphologies in VessMorphoVis. 

You can see some examples in the attached images. 

![Screenshot from 2020-06-04 18-34-58](https://user-images.githubusercontent.com/1279443/83785773-1a9aa580-a692-11ea-89a9-48f8df008675.png)

**Comment by wizmer** [comment]
Resampling is a high-level functionality which is not IO related. Hence, it does not belong to MorphIO. Moreover, sampling can be implemented in many different ways depending on the goal to achieve.

Eventually, that could be part of https://github.com/bluebrain/morph-tool but keep in mind that this is a python package so it might not be as efficient as a C++ code if that matters.
