### ISSUE TITLE
Loading custom error marker from .asc

### ISSUE THREAD

**Issue by arnaudon** [BlueBrain/MorphIO#226]
We generate marker data on morphologies, which are of this type, at the end of the .asc file:

```                                                                  
(Circle6   ; MUK_ANNOTATION                                           
    (Color Magenta)   ; MUK_ANNOTATION                                
    (Name "dangling")   ; MUK_ANNOTATION                              
    (     -1.37      -8.97     -10.92 0.50)   ; MUK_ANNOTATION        
    (     -2.59       9.52      13.46 0.50)   ; MUK_ANNOTATION        
)   ; MUK_ANNOTATION  
```
and  produce an error such as this:
```
RawDataError: 
morph.asc:5019:error
Unexpected token
Expected: LPAREN but got  Consume
```
whereas markers obtained from external sources can be red with: https://github.com/BlueBrain/MorphIO/pull/186

**Comment by wizmer** [comment]
I think all we need to do is to replace `Circle6` by `(Circle6)` but we first need to find out if Neurolucida would still be able to read the annotation (I think that yes).

**Comment by mgeplf** [comment]
> but we first need to find out if Neurolucida would still be able to read the annotation (I think that yes).

This should be followed up on; can you create an example for Ying Shi to test, and make a ticket?

**Comment by arnaudon** [comment]
That's my plan of today!

**Comment by wizmer** [comment]
> I think all we need to do is to replace Circle6 by (Circle6) but we first need to find out if Neurolucida would still be able to read the annotation (I think that yes).

I think this is not accurate. `Circle6` (without parentheses) is supposed to be a valid marker anyway so I think there is no need to bother Ying. We can keep the annotation as they are.

**Comment by mgeplf** [comment]
Can all the markers have numeric endings? (ie: DoubleCircle?)

Also, are the numeric endings unbounded? (ie: is Circle123412341234?)

**Comment by wizmer** [comment]
I don't know since as you know we have no Neurolucida specification.
But I have broaden the use case in https://github.com/BlueBrain/MorphIO/pull/229
