### ISSUE TITLE
Introduce a flag/constructor argument to raise warning as errors instead of printing them

### ISSUE THREAD

**Issue by asanin-epfl** [BlueBrain/MorphIO#262]
Currently there is no proper way to detect warnings programmatically from MorphIO except parsing stderr. Would be good to raise errors or somehow wrap those warning as Python warnings. I have no preference. Anything to catch them programmatically on Python side.

**Comment by tomdele** [comment]
I don't think we can wrap these as python warnings. The warnings are just printed strings and we do not throw / return anything.
We can maybe add a flag to throw instead but this is a bit weird. I need to think about it

**Comment by asanin-epfl** [comment]
> We can maybe add a flag to throw instead but this is a bit weird. 

This will work for me

**Comment by mgeplf** [comment]
> The warnings are just printed strings

A library writing output seems weird to me; it should be programatically handle-able.

There are only a few files that are writing to `cout`/`cerr`:
```
src/properties.cpp
include/morphio/section_base.tpp
src/errorMessages.cpp
src/vasc/section.cpp
```
Those should be cleaned up.

Note that `morphio.set_maximum_warnings(int)` allows one to set the errors printed; and iirc, there is a way to get a log of the errors, but I don't see it in a quick pass of the doc.

**Comment by asanin-epfl** [comment]
> Those should be cleaned up.

How to clean up? I see a min and a max solution. The min is to rename `void printError`  to `void raiseError`, raise instead of printing inside this function. The max solution is to create an appropriate Exception class hierarchy because currently exceptions are functions(one function per exception type) with a tangled mix of `enum Warning` and `enum ErrorLevel`.
