### ISSUE TITLE
Should MorphIO warn about wrong root point for 3 point soma?

### ISSUE THREAD

**Issue by asanin-epfl** [BlueBrain/MorphIO#279]
@mgeplf, @tomdele  according to https://github.com/BlueBrain/MorphIO/issues/273#issuecomment-816474518, we agreed that MorphIO allows for 3 point sequential swc soma (left bottom picture in the mentioned comment). MorphIO currently gives a warning about such soma by this code https://github.com/BlueBrain/MorphIO/blob/master/src/readers/morphologySWC.cpp#L298. My question should we keep this warning or did it become obsolete?

**Comment by mgeplf** [comment]
So, it seems to be added in:
https://github.com/BlueBrain/MorphIO/commit/d7785206331040a9942f66d6190772096ace0fd7

And has to do with whether the neurite comes off the intial point or a latter one.  I don't see why it can't be a latter one.

What does NEURON do?

**Comment by asanin-epfl** [comment]
> What does NEURON do?

NEURON 7.8.2 implicitly changes soma. For example
```
1 1 1 0 1 4.0 -1
2 1 2 0 0 4.0 1
3 1 3 0 0 4.0 2
```
is interpreted as
```
[[-3.  0.  1.  8.]
 [ 1.  0.  1.  8.]
 [ 5.  0.  1.  8.]
 [ 2.  0.  0.  8.]
 [ 3.  0.  0.  8.]]
```

NEURON 8.0 will read it as is without any changes/warnings
```
[[1. 0. 1. 8.]
 [2. 0. 0. 8.]
 [3. 0. 0. 8.]]
```

**Comment by mgeplf** [comment]
Since we're not going to transform the soma, let's pick the NEURON 8.0 behavior.

The question I have is, what does NEURON v8 do with:
```
1 1 1 0 1 4.0 -1
2 1 2 0 0 4.0 1
3 1 3 0 0 4.0 2
4 2 4 4 4 4    1  # branch for 'start' of soma 
5 2 5 5 5 5    2  # branch for 'middle' of soma 
6 2 6 6 6 6    2  # branch for 'end' of soma 
```

**Comment by asanin-epfl** [comment]
Well, it's a good question. Results are good in my opinion except we can question how axon diameters were reconstructed.
For the morphology you mentioned the results are:
```
8.0a-506-g3b0be29f
three-point-soma.swc
soma points
[[1. 0. 1. 8.]
 [2. 0. 0. 8.]
 [3. 0. 0. 8.]]
axon points
[[ 1.  0.  1.  8.]
 [ 4.  4.  4.  8.]
 [ 2.  0.  0. 10.]
 [ 5.  5.  5. 10.]
 [ 2.  0.  0. 12.]  # minor note. In the posted morphology there is a typo, and branch for 'end' of soma actually starts from 2
 [ 6.  6.  6. 12.]]
```

Here is the code I used to verify:
```python
import neuron
import numpy as np
from neuron import h,gui

h.load_file('import3d.hoc')


class Cell():
  def __init__(self, fname, gid):
    self._gid = gid
    self.fname = fname
    self.load_morphology(fname)
  def load_morphology(self, nom):
    print(nom)
    cell = h.Import3d_SWC_read()
    cell.input(nom)
    i3d = h.Import3d_GUI(cell, 0)
    i3d.instantiate(self)
  def __str__(self):
    return 'Cell[{}]'.format(self._gid)


def get_seclist_points(seclist):
  points = []
  for sec in seclist:
    for i in range(sec.n3d()):
      points.append([sec.x3d(i), sec.y3d(i), sec.z3d(i), sec.diam3d(i)])
  return np.array(points)


print(neuron.__version__)
cell = Cell('three-point-soma.swc', 0)

print('soma points')
print(get_seclist_points(cell.soma))
print('axon points')
print(get_seclist_points(cell.axon))
```

**Comment by asanin-epfl** [comment]
I'm closing the issue as everything is fine. The problem arises only when a neurite is not connected to the 1st soma point. Sequential ids alone don't cause this warning.

**Comment by mgeplf** [comment]
> # minor note. In the posted morphology there is a typo, and branch for 'end' of soma actually starts from 2

Ahem, thanks.

> The problem arises only when a neurite is not connected to the 1st soma point.

So we should allow it connecting to any of the soma points in the swc case, right?

**Comment by asanin-epfl** [comment]
> So we should allow it connecting to any of the soma points in the swc case, right?

ok, I will create a ticket for that
