### ISSUE TITLE
Support "Cell Body" for ASC files

### ISSUE THREAD

**Issue by genric** [BlueBrain/MorphIO#300]
After discussing this today, we probably want to support "Cell Body" definition format as, due to historical reasons, there are morphologies using that soma definition format and other tools are able to process them.
Example morphology:
http://neuromorpho.org/dableFiles/jonas/Source-Version/02022018_252Lgc11.ASC
available here: http://neuromorpho.org/neuron_info.jsp?neuron_name=02022018_252Lgc11)

Looks like there was a similar issue(#264) related to "Cell Body" and there was a PR to support them.

**Comment by asanin-epfl** [comment]
There is an attempt to implement it already in #39.
