### ISSUE TITLE
New release to avoid submodule issues

### ISSUE THREAD

**Issue by matz-e** [BlueBrain/MorphIO#315]
The submodule `https://github.com/wizmer/lexertl.git` of 3.1.1 has disappeared. We should have a new release to avoid future issues.

**Comment by mgeplf** [comment]
I've asked @wizmer to bring it back (and made a copy at https://github.com/mgeplf/lexertl he can use to make it come back).

We'll be cutting a release in the next few days, but that prob. doesn't help you right now.

**Comment by mgeplf** [comment]
The old repo is back, and a new release will be added in the coming days.
