### ISSUE TITLE
unable to install morphio in Windows

### ISSUE THREAD

**Issue by jaehongpark-neuro** [BlueBrain/MorphIO#318]
Hi,

I didn't have a problem to install your package until early this year.

However, recently I formatted my laptop and got a new computer, so I tried to install anaconda3 and morphio in Windows10 again, but some errors returned to me.

https://github.com/brainglobe/brainrender/issues/159 

it looks like morphio requires CMake, which also requires Visual studio.

So should I install visual studio first, and then install CMake then try to install morphio??
Previously I didn't install visual studio but it was fine, so I was wondering what happens now.

Thanks

**Comment by mgeplf** [comment]
> I didn't have a problem to install your package until early this year.

Could you try installing an older package, so we can potentially narrow the problem down?

I'm not super familiar with `anaconda3`, but IIRC, it should not require Visual Studio - perhaps it would be worth trying to install cmake within anaconda: `conda install -c anaconda cmake` or some such?

**Comment by mgeplf** [comment]
No update in a while, closing.
