### ISSUE TITLE
Problems with Windows installation

### ISSUE THREAD

**Issue by jofrony** [BlueBrain/MorphIO#322]
Hi,

I was trying to install neurom on windows and had problems with morphio.
The issue was cmake and visual studio. I installed the appropriate version but it still did not work. 

Is there an alternative?

**Comment by mgeplf** [comment]
Sorry, I missed this.

I'm trying to find time to build windows wheels, so one shouldn't need to build it themselves - but that doesn't help you if you're using the `c++` interface.

Can you post the errors that you got, and what you tried?

**Comment by Helveg** [comment]
@mgeplf look into [`cibuildwheel`](https://github.com/pypa/cibuildwheel), they can build entire wheelhouses and drastically reduce the burden on maintainers :)

**Comment by mgeplf** [comment]
@Helveg >  look into cibuildwheel

Thanks; we're already using it:
https://github.com/BlueBrain/MorphIO/blob/master/.github/workflows/publish-sdist-wheels.yml#L36

The problem was that we don't have as much windows experience, so things like getting the right Visual Studio toolkit to work and such is difficult.  I'm close to getting it to work, but it's slow going.

**Comment by mgeplf** [comment]
Sorry, I was on vacation; we are building morphio wheels:

https://pypi.org/project/MorphIO/#files

Do those work for you @Peter-Hogg / @Helveg?

**Comment by Helveg** [comment]
Nice! Yes, things seem to work at first sight :)

```
PS > pip install morphio
Collecting morphio
  Downloading MorphIO-3.3.2-cp39-cp39-win_amd64.whl (527 kB)
     |████████████████████████████████| 527 kB 6.8 MB/s
Requirement already satisfied: numpy>=1.14.1 in c:\users\robin\appdata\roaming\python\python39\site-packages (from morphio) (1.20.1)
Requirement already satisfied: h5py<4,>=3 in c:\users\robin\appdata\roaming\python\python39\site-packages (from morphio) (3.1.0)
Installing collected packages: morphio
Successfully installed morphio-3.3.2
```

And:

```
PS > python
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import morphio
>>> dir(morphio)
['Annotation', 'AnnotationType', 'CellFamily', 'CellLevel', 'DendriticSpine', 'EndoplasmicReticulum', 'GlialCell', 'IDSequenceError', 'IterType', 'LogLevel', 'MissingParentError', 'MitoSection', 'Mitochondria', 'MitochondriaPointLevel', 'MorphioError', 'Morphology', 'MultipleTrees', 'Option', 'PointLevel', 'Points', 'PostSynapticDensity', 'Properties', 'RawDataError', 'Section', 'SectionBuilderError', 'SectionLevel', 'SectionType', 'Soma', 'SomaError', 'SomaType', 'UnknownFileType', 'VasculatureSectionType', 'Warning', 'WriterError', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_morphio', 'mut', 'ostream_redirect', 'platform', 'set_ignored_warning', 'set_maximum_warnings', 'set_raise_warnings', 'vasculature', 'version']
```

**Comment by Peter-Hogg** [comment]
> 
> 
> Sorry, I was on vacation; we are building morphio wheels:
> 
> https://pypi.org/project/MorphIO/#files
> 
> Do those work for you @Peter-Hogg / @Helveg?
I tested it out and it worked! Thanks for fixing this!

**Comment by mgeplf** [comment]
Great - sorry it took so long, windows isn't something I have much experience with.

I'm going to close this, but feel free to reopen if you run into other problems.
