### ISSUE TITLE
Parsing  of 'Incomplete' markers

### ISSUE THREAD

**Issue by arnaudon** [BlueBrain/MorphIO#323]
It could be nice to somehow retrieve the 'Incomplete' markers from morphio python API, such as this one:

https://github.com/BlueBrain/MorphIO/blob/5a71472f425a1cb336212dfe871cadabaf1a84af/tests/test_2_neurolucida.py#L486

**Comment by asanin-epfl** [comment]
`Incomplete` are not markers according to the source files of [morphologyASC.cpp](https://github.com/BlueBrain/MorphIO/blob/master/src/readers/morphologyASC.cpp). It has to be decided how to represent 'Incomplete' as they don't have points as usual markers. For example there is an 'Incomplete'. How to represent it on the morphology? You would probably need to understand where it is located within the morphology.

**Comment by arnaudon** [comment]
You mean this: https://github.com/BlueBrain/MorphIO/blob/master/src/readers/morphologyASC.cpp#L33
and this? https://github.com/BlueBrain/MorphIO/blob/master/src/readers/morphologyASC.cpp#L49
The incomplete is not a marker indeed, it's a 'tag' on leave sections. 

From my basic knowledge of morphio, I can see something like `section.is_complete`, similar to `section.is_root`, which is True by default, unless the section is followed by the `Incomplete` tag in the file?

**Comment by asanin-epfl** [comment]
> You mean this: ...

Rather this https://github.com/BlueBrain/MorphIO/blob/master/src/readers/lex.cpp#L202 but that's not relevant. 'Incomplete' is not a marker.

> From my basic knowledge of morphio, I can see something like section.is_complete, similar to section.is_root, which is True by default, unless the section is followed by the Incomplete tag in the file?

That's interesting. However HDF5 and SWC files don't have 'Incomplete'. For them it would always be empty. What's the point of it then? If there is a property `incomplete` on the morphology instance then what would you want to see inside this property?

**Comment by arnaudon** [comment]
Yes, this is specific to ascii files generated by neuroluscida, so if it cannot be made optional (like if .asc with such tags then we have .is_complete), then set it to True by default (no info means it is complete). 

What we would need is the list of incomplete leave sections from these tags, one way or another. Maybe `morph.incomplete_sections = [sec_id1, sec_id2, ...]` ? Just go for the simplest option, we can change the format as we wish later in python. 

This is only something we want to read with morphio, and then discard later when we process morphologies. What I do with markers is the same, I read them from the .asc file, and save them in my own format so that can use them as I want in python. With mut, when we save the morpho again, all markers disappear, which is good, so only the morphology data remains.

**Comment by mgeplf** [comment]
Adding API features like `section.is_complete` is beyond the scope of this library; we can't support all of the non-documented features of neurolucida.

If you want to check if there are incompletes in the file, a simple grep will get that info, and it can be fed back to whoever gave the morphology in the first place, so that it is fixed, no?

**Comment by arnaudon** [comment]
These cannot be fixed, as they are cut leaves. They will basically provide us with ground truth for cut leaves. They manually add this tag to say that they know it is not the real termination, but they cannot reconstruct it. One way or another, it would be nice to have a tool to read them, that's my only point here. How, I don't know! I also thought about a simple pythonic parser, but aleksei told me it is not so simple to do, due to the possible complex nature to the text in these files.

**Comment by arnaudon** [comment]
Just tried to parse it myself here: https://github.com/BlueBrain/morph-tool/pull/76
this is satisfactory for me atm, so if you feel this is to much to have in morphio, we'll just clean up and test my function and merge in morph-tool.

**Comment by mgeplf** [comment]
With the addition of marker having `parent_id` in https://github.com/BlueBrain/MorphIO/pull/325 (which I still have to review); I think the original idea of having Incomplete as a marker makes more sense?  Perhaps that's away it can be added w/o impacting the rest of the API much.

**Comment by asanin-epfl** [comment]
@arnaudon do you have any feedback here?

**Comment by arnaudon** [comment]
It works for me, I close this, thank you very much for the fast implementation of that!
