### ISSUE TITLE
Markers are only parsed if at the top/botom of file

### ISSUE THREAD

**Issue by arnaudon** [BlueBrain/MorphIO#324]
But not if in the middle, as in this example:

```
(FilledCircle
    (Color Red)
    (Name "Marker detected 1")
    (  451.82  -244.42   -20.80     0.09)  ; 1
  )  ;  End of markers

("CellBody"                                     
  (Color Green)
  (CellBody)                                    
  (  435.99  -231.01   -20.29     0.24)  ;  1, 1
)  ;  End of contour

( (Color RGB (0, 221, 0))                                             
  (Axon)
  (  453.15  -243.36   -21.06     3.30)  ; Root                       
  (  454.26  -242.59   -19.77     2.89)  ; 1, R                       
                                                                      
  (FilledCircle                                                       
    (Color RGB (0, 221, 0))                                           
    (Name "Marker undetected 1")                                      
    (  453.05  -243.48   -20.80     0.09)  ; 1                        
  )  ;  End of markers                                                
   Incomplete                                                         
)  ;  End of tree                                                     
                                                                      
( (Color Red)                                                         
  (Dendrite)                                                          
  (  450.09  -243.77   -21.14     3.72)  ; Root                       
  (  451.99  -244.35   -21.18     3.72)  ; 1, R                       
                                                                      
  (FilledCircle                                                       
    (Color Red)                                                       
    (Name "Marker undetected 2")                                      
    (  451.82  -244.42   -20.80     0.09)  ; 1                        
  )  ;  End of markers                                                
  (                                                                   
    (  469.69  -257.10   -22.37     1.17)  ; 1, R-1                   
    (  470.64  -258.24   -22.32     0.87)  ; 2                        
  ) 
) 
(FilledCircle
    (Color Red)
    (Name "Marker detected 2")
    (  451.82  -244.42   -20.80     0.09)  ; 1
  )  ;  End of markers
```
Would it be possible to detect them as well, so that  `morphio.Morphology('morph.asc').markers` has them all? 

Thank you!

**Comment by asanin-epfl** [comment]
Do you need it for all types of markers or only for "Incomplete" markers?

**Comment by arnaudon** [comment]
Ah sorry, this one is not about Incomplete, but 'normal markers'. I named the 2 markers which are not detected by morphio as `undetected`. The incomplete marker is in the other issue.

**Comment by asanin-epfl** [comment]
According to https://github.com/BlueBrain/MorphIO/pull/186#issue-414001806 only a top-level text can be a marker. Your inquiry breaks this. Is Lida aware of (can confirm) this change?

**Comment by arnaudon** [comment]
Yes, I think @lidakanari even had her own marker parser a while back. These inner markers have been given to us by collaborators, so they exist. Afaik, Benoit told me because neuroluscida is not open source, there is not spec for this, so my guess is that he wrote that given the example files he had at the time. Would implementing this change be breaking in some ways? Maybe we can move all markers to the top level before parsing with mophio?

**Comment by asanin-epfl** [comment]
> Would implementing this change be breaking in some ways?

I don't know. Should be ok from what I see.

> Maybe we can move all markers to the top level before parsing with mophio?

This would be wrong to do. MorphIO should handle them normally if that is required.

**Comment by arnaudon** [comment]
I just asked, and these markers can be generated with Neuroluscida, so we should be able to load them imo. Let me know if I can help on that!

**Comment by asanin-epfl** [comment]
ok, this would require some refactoring of existing code. You can create test data that is important to work for your case.

**Comment by arnaudon** [comment]
Mmh ok, is this hard to do? You can use the example I put in the description, it has what I need so far.

**Comment by asanin-epfl** [comment]
> Mmh ok, is this hard to do?

Well, it's not simple as I would like it to be :D

**Comment by asanin-epfl** [comment]
Would it be sufficient for you to keep markers at `Morphology` level? Do you need them to be attached to `Section` as well?
`morphio.Morphology('morph.asc').sections[0].markers` ?

**Comment by arnaudon** [comment]
No, I think it's enough to have them in the global list of markers, otherwise we will never find them haha. Also, they have the xyz position in them, so we know where they are, and can look for closest sections if we need.
If this is too simple for you to implement, you could add an option `morph.markers[0].sec_id = [section id of the marker if not global]` ?

**Comment by asanin-epfl** [comment]
> Also, they have the xyz position in them

How is that? From what I see there can be markers with label text only. What is their xyz position?

**Comment by arnaudon** [comment]
Sorry, I'm talking about the 
```
  (FilledCircle                                                       
    (Color RGB (0, 221, 0))                                           
    (Name "Marker undetected 1")                                      
    (  453.05  -243.48   -20.80     0.09)  ; 1                        
  )  ;  End of markers  
```
the `Incomplete` ones are another story, no? I put an issue here: https://github.com/BlueBrain/MorphIO/issues/323

**Comment by asanin-epfl** [comment]
@arnaudon do you have any feedback here?

**Comment by arnaudon** [comment]
It works for me, thanks! I'll close this then.

**Comment by lidakanari** [comment]
@asanin-epfl thanks a lot for the fix, it works great for loading the markers. One relevant question. I can create a separate issue if you think it makes sense. I noticed that the markers that are loaded are not consistently saved in the output file. As a result, we will lose markers when we curate the data. Is this the expected behavior and should we modify it accordingly? Thanks, Lida

**Comment by arnaudon** [comment]
Yes, this was the agreed behavior, in MCAR, we save them in a separate marker file, so the .asc file is clean of any marker (only this format can allow marker, so they will be lost if the format is changed).

**Comment by asanin-epfl** [comment]
Hi! as @arnaudon noted markers are not saved with MorphIO. You can create an issue for that. I'm not sure whether it will be implemented anytime soon. Up to @mgeplf to decide.

**Comment by lidakanari** [comment]
Thanks for your input @asanin-epfl. Sure, we should first decide what is the expected outcome and I will create the ticket accordingly.
