### ISSUE TITLE
Support external pybind11

### ISSUE THREAD

**Issue by musicinmybrain** [BlueBrain/MorphIO#337]
In general, `pybind11` supports use with `add_subdirectory(extern/pybind11)` or from an install with `find_package(pybind11 CONFIG)` (https://pybind11.readthedocs.io/en/stable/cmake/index.html, https://pybind11.readthedocs.io/en/stable/compiling.html#building-with-cmake).

I’ve tried to do this downstream in Fedora Linux, but couldn’t manage to untangle CMake enough to get it working properly in this particular case. An `EXTERNAL_PYBIND11` option, similar to the existing `EXTERNAL_HIGHFIVE`, would be a big help!

This isn’t a critical issue, as Fedora Linux guidelines do allow us to continue to bundle `pybind11` as long as upstream does not support building with an external copy.

**Comment by mgeplf** [comment]
That seems reasonable; on the one hand it's a header only library, but on the other I appreciate people who are doing the heavy lifting of packaging things.

> This isn’t a critical issue, 

Is there a timeline for that, so I can prioritize it appropriately?  I'm pretty overwhelmed at the moment.

Thanks!
