### ISSUE TITLE
Axon on dendrites not saved to ascii format

### ISSUE THREAD

**Issue by arnaudon** [BlueBrain/MorphIO#361]
I just noticed the following, which imo, should have a warning to prevent users of what is happening.

Take the toy morphology below, open with morphio, then save to a .asc file. You'll see the axon sections will become basal sections.

``` 
1 1  0  0 0 1. -1
 2 3  0  0 0 1.  1
 3 3  0  5 0 1.  2
 4 3 -5  5 0 1.5 3
 5 3  6  5 0 1.5 3
 6 2  0  0 0 1.  3  # we connect axon to basal here
 7 2  0 -4 0 1.  6
 8 2  6 -4 0 2.  7
 9 2 -5 -4 0 2.  7
```

**Comment by arnaudon** [comment]
Ah, I just realised, of course .asc files don't allow for that... So maybe better to put a huge warning, and maybe connect axon to soma before saving, which is less dramatic than converting whole axon to basal.

**Comment by mgeplf** [comment]
> Ah, I just realised, of course .asc files don't allow for that.

We haven't seen one, but maybe there is some that they do to make it possible.
Do you think you could ask whoever has a copy of microbright to try and make an axon extend from a dendrite?

> So maybe better to put a huge warning, and maybe connect axon to soma before saving, which is less dramatic than converting whole axon to basal.

It should fail; if it tries to be 'smart' about handling it, the behavior will be surprising.  @eleftherioszisis can you make it fail once we've confirmed that `.asc` can't magically handle heterogenous trees?

**Comment by eleftherioszisis** [comment]
I agree that it should throw an exception if a morphology with heterogeneous trees is written in ascii format.

**Comment by arnaudon** [comment]
I'm asking ying, I'll report here once I have more info

**Comment by arnaudon** [comment]
Maybe it would make sense to attach each neurite to the closest section? It may be tricky near soma...

**Comment by arnaudon** [comment]
Sorry, you're right werner, I didn't realise at first. asc does not care about attaching neurites to any other part of the dendrite, so it trivially handles the axon on dendrite case. The issue is just morphio. Can't we fix morphio so that it creates the same .asc file as one expect, instead of raising? Morphio does not care about neurites, so it should be possible here, without discussing the definition of neurite.

**Comment by eleftherioszisis** [comment]
I would like to make the following clarification: MorphIO will not mutate the data in any way as it's beyond its purpose as an IO tool. If a writing format cannot support how the data is represented in another format, the best solution as Mike suggested is to fail. MorphIO should not fix or make implicit decisions for what would be best to do. It should be a dead-simple data structure mapping to the underlying data stored in the file as best as possible given the different data files.

An `is_heterogeneous` option will be added on the sections that will allow identifying if the tree downstream or upstream is heterogeneous.

It still remains to be determined if a dedicated SectionType is required for the `axon_carrying_dendrite` part of the heterogeneous axon-carrying-dendrite trees.

**Comment by arnaudon** [comment]
I understand you guys like heterogenous stuff, and as I'm not a maintainer of morphio/neurom, I can only complain with creating issues/PR. 

But: if you .asc file has an axon on a dendrite far from soma, morphio will attach it to soma, which not correct.

**Comment by lidakanari** [comment]
The data from the experimental labs are in asc but encode this behavior, because they see these axons starting from dendrites in the lab. I will provide an example as soon as I have one from Ying.

However, the .asc saved from morphio is not exactly the same as what we get from neurolucida. My suspicion is this transformation might be the culprit for this issue. Again the main issue is the lack of proper documentation for the neurolucida asc format but they refuse to provide one.

**Comment by arnaudon** [comment]
can you guys read this? https://github.com/neuronsimulator/nrn/blob/99a6a370ef143b3c681eda1deea68bc7e2b8f21d/share/lib/hoc/import3d/read_nlcda3.hoc#L440

**Comment by eleftherioszisis** [comment]
Yeah, what's wrong with that?

**Comment by arnaudon** [comment]
I can't read this code, but I wanted to know how it would attach axon far away from soma. I can try to load a morph to see.

**Comment by wvangeit** [comment]
Never seems to be called by neuron though. But surprise surprise it was asked for by Michele Migliore. Afaik this issue is fairly common in hippocampus. 
https://github.com/neuronsimulator/nrn/pull/781

**Comment by arnaudon** [comment]
Just checked with a test morph, and it's doing as morphio, attaching a far way axon to soma: 

```
In [8]: h.topology()

|-|       test[0].soma[0](0-1)
  `|       test[0].dend[0](0-1)
    `|       test[0].dend[1](0-1)
    `|       test[0].dend[2](0-1)
  `|       test[0].axon[0](0-1)
    `|       test[0].axon[1](0-1)
    `|       test[0].axon[2](0-1)
```

**Comment by wvangeit** [comment]
But so i assume that if you call connect_axon_nearest it might connect it to the nearest dend

**Comment by mgeplf** [comment]
Was just looking at that same PR.  Best on the descrition, is this the transformation:
![image](https://user-images.githubusercontent.com/13150119/145601088-3e8d7ec0-c79f-4b88-9c26-e6f30616455d.png)
(ie: blue axon attached to dendrite?  I guess it might also connect it to a soma point?)

**Comment by arnaudon** [comment]
@wvangeit , not sure how to call this function... but this works
```
In [10]: cell.icell.axon[0].connect(cell.icell.dend[2])
Notice: test[0].axon[0](0) had previously been connected to parent test[0].soma[0](0.5)
Out[10]: test[0].axon[0]

In [11]: h.topology()

|-|       test[0].soma[0](0-1)
  `|       test[0].dend[0](0-1)
    `|       test[0].dend[1](0-1)
    `|       test[0].dend[2](0-1)
      `|       test[0].axon[0](0-1)
        `|       test[0].axon[1](0-1)
        `|       test[0].axon[2](0-1)
```

**Comment by arnaudon** [comment]
My bad, hines was showing it. Yes, my morph ends up good if I call that. So one has to call this function to properly load these morphs in neuron, interesting!

**Comment by arnaudon** [comment]
So the definition of neurite in neuron does not assume it is connected to soma. In fact, from his little example from https://nrn.readthedocs.io/en/latest/python/modelspec/programmatic/topology.html?highlight=topology 

```
from neuron import h, gui
soma = h.Section(name='soma')
axon = h.Section(name='axon')
dend = [h.Section(name='dend[%d]' % i) for i in range(3)]
for sec in dend:
    sec.connect(soma(1), 0)

h.topology()
s = h.Shape()
```
it is clear that one can connect a neurite wherever he/she wants. But it's not really a neurite, these are root_sections, as in morphio (I think!).
