### ISSUE TITLE
saving custum types in .asc

### ISSUE THREAD

**Issue by arnaudon** [BlueBrain/MorphIO#369]
We just bumped into this obscure error if we do the following (from neurom):

```
m = nm.load_morphology('test.asc')
for section in m.neurites[0].iter_sections():
    section.morphio_section.type = SectionType.custom5
m.write('test_custom.asc')
```

we get this crash:

```
----> 1 m.write("t.asc")

IndexError: map::at
```

Saving to .swc works, I guess in .asc one has to map the custom types to a header name of the section list, or something like that? 

It's not at all urgent at all, it's just to let you know!

**Comment by mgeplf** [comment]
Thanks for the great bug-report; we'll look into it.

**Comment by arnaudon** [comment]
Always a pleasure to report bugs without trying to find a fix! :)

**Comment by eleftherioszisis** [comment]
Hi Alexis. Would that entail we should allow writing the swc custom properties in the ascii format? Even though these types are not specified/available for ascii files, I don't see any harm in making them available to and fro that format.

**Comment by mgeplf** [comment]
Perhaps we have to throw an exception, unless the types we know exist in ASC exist?  If someone w/ access to neurolucida can list all the types, we can have those; and anything else throws?

**Comment by arnaudon** [comment]
Yes, whatever you prefer, it just happened to our MSc student, and it's an impossible crash to understand as it is. Indeed, if we really need to save this in a file, we'd better use the format that allows this custom types. Maybe throw an error saying we can only save these custom types in .swc format?

**Comment by arnaudon** [comment]
but again, it's not urgent at all, we don't need to save these custom (we revert back to normal section types before saving).

**Comment by mgeplf** [comment]
FYI I skimmed this (https://youtu.be/Q7xztgAMBh8?t=948), and it looks like the drop down box only has these options:
![image](https://user-images.githubusercontent.com/13150119/150494159-d241e238-d74a-4d4e-9e8a-1314736690fb.png)

> Maybe throw an error saying we can only save these custom types in .swc format?
Seems best to me.
