### ISSUE TITLE
precision in soma warnings

### ISSUE THREAD

**Issue by arnaudon** [BlueBrain/MorphIO#371]
Good morning! I'm just having loads of these:
```
Warning: the soma does not conform the three point soma spec
The only valid neuro-morpho soma is:
1 1 x   y   z r -1
2 1 x (y-r) z r  1
3 1 x (y+r) z r  1

Got:
1 1 7019.1 748.275 3409.77 5.15927 -1
2 1 7019.100098 743.115723 3409.774902 5.159274 1
3 1 7019.100098 753.434265 (exp. 753.434326) 3409.774902 5.159274 1
```
is there a way to set the precision for these warnings? As you see the diff is in the 4th digit, which is perfectly acceptable. I would do max 2 digits, given these points are marked on an image, it cannot be as precise as 0.0001 microns!

Have a nice day!

**Comment by eleftherioszisis** [comment]
0.0001 microns is a bit excessive, I agree. Out of curiosity, is this a morphology that you have loaded or a test example to exhibit the issue?

0.01 microns accuracy for the check sounds good to me.

**Comment by arnaudon** [comment]
It's an SEU morphology (from external collaborators).

**Comment by eleftherioszisis** [comment]
Just for reference, the check does not specify precision at all. They have to be identical:
https://github.com/BlueBrain/MorphIO/blob/65f21e6df33096c42dc0b1b1ad144786bebf91b1/src/readers/morphologySWC.cpp#L225-L235

**Comment by mgeplf** [comment]
> given these points are marked on an image,

I didn't know they were doing it manually; my understanding of these morphologies was that it was an extension by [neuromporph|http://neuromorpho.org/SomaFormat.html] as a transformed version of other somas.
`The x and z coordinates as well as the radius of both the second and third soma points are the same as that of the first point.`

We're relying on the 'are the same' to reliably detect these types of soma, and handle them properly.

**Comment by arnaudon** [comment]
ah ok, so maybe it's just numerical accuracy lost between codes/file format in this case.
