### ISSUE TITLE
Would it be possible to update the bundled submodules to latest releases/snapshots please?

### ISSUE THREAD

**Issue by sanjayankur31** [BlueBrain/MorphIO#390]
The following submodules are using quite old versions of the bundled software:

- gsl-lite is using a snapshot from 2018. the current version is 0.40.0 from November 2021
- highfive is 2.2.2 from july 2020, current release is 2.3.1 from august 2021
- lexertl14 is a snapshot from may 2021, current master is at Feb 2022.

I totally understand that bundling third party tools using git-submodules is very convenient for CI etc., but I guess perhaps a task needs to be added to update these to the latest versions from time to time, maybe once every release? Otherwise we run into the primary issue with bundling copies of software---using outdated versions of software. 

---

For context, I'm part of the maintenance team that maintains MorphIO in Fedora for the NeuroFedora team. We use system libraries wherever possible, and system libraries are constantly updated in Fedora to their latest releases. So our builds differ from upstream builds now, because the versions of bundled software here are not the current releases. Since MorphIO is used by other tools like NeuroM, small differences in MorphIO output can propagate to NeuroM and so on. (see https://github.com/BlueBrain/NeuroM/issues/983, for example).

**Comment by eleftherioszisis** [comment]
@sanjayankur31 , thanks for bringing this to our attention. I have updated the bundled software to their respective latest versions.

**Comment by sanjayankur31** [comment]
Thanks very much @eleftherioszisis :rocket:
