### ISSUE TITLE
Better 'diameter' field in ASC writer

### ISSUE THREAD

**Issue by mgeplf** [BlueBrain/MorphIO#409]
Based on feedback from @arnaudon, @lidakanari and @wvangeit, it's clear we can handle writing ASC files better:
1) The diameter column for CellBody points is used to display the contour line thickness in neurolucida (see attached 
soma2.asc / soma3.asc)
2) single point contours don't make sense (see soma1.asc)
(ASC files are renamed txt to to github accepts them)

![soma1](https://user-images.githubusercontent.com/13150119/169769870-8935b07d-df29-48d5-975a-49a86fe5e4b1.png)
![soma2](https://user-images.githubusercontent.com/13150119/169769868-ddb82e3c-67a6-4ebd-8513-781d1bd57873.png)
![soma3](https://user-images.githubusercontent.com/13150119/169769865-ff3cde2d-a414-446c-8e45-9092f2ec6484.png)

[soma1.txt](https://github.com/BlueBrain/MorphIO/files/8752534/soma1.txt)
[soma2.txt](https://github.com/BlueBrain/MorphIO/files/8752533/soma2.txt)
[soma3.txt](https://github.com/BlueBrain/MorphIO/files/8752532/soma3.txt)

**Comment by mgeplf** [comment]
Handling of the conversion is better done in morph-tool; doing it there:
https://github.com/BlueBrain/morph-tool/pull/102

**Comment by arnaudon** [comment]
this is done

**Comment by mgeplf** [comment]
Strange, I will do it.
