### ISSUE TITLE
issue with swc morphology

### ISSUE THREAD

**Issue by arnaudon** [BlueBrain/MorphIO#419]
This morphology is not loadable in morphio: [fail.swc.zip](https://github.com/BlueBrain/MorphIO/files/9044455/fail.swc.zip)
with error:
```
MissingParentError: 
test_2.swc:1770:error
Sample id: 1770 refers to non-existant parent ID: 0
```
while when the last line is removed from the file, it can be loaded, and result in a single axon morphology. 

@lidakanari @eleftherioszisis , would you have any idea what is going on? It is a morphology for @YannRoussel

**Comment by mgeplf** [comment]
Very strange, I will look into.  I can repro with that file.

**Comment by mgeplf** [comment]
It appears `sscanf` from https://github.com/BlueBrain/MorphIO/blob/d4931369266bc24c5f283c7d04d779d02e3ae4a7/src/readers/morphologySWC.cpp#L32 is reading the line:
```
1770 2 186.598095783431 -0.0017926065475997177 71.47192685817814 0.1144 1769
```
as (not: I'm not printing as many sigfig):
```
1770                   2          186.598099           -0.001793           77.000000           71.471924                   0
```

**Comment by lidakanari** [comment]
Very peculiar... I don't have any insights from my side. the file seems to be as expected from the file format point of view

**Comment by mgeplf** [comment]
@arnaudon / @YannRoussel can you try the wheels created by CI (in the dist.zip):
https://github.com/BlueBrain/MorphIO/actions/runs/2615023036

To see if that fixes the issue?

**Comment by arnaudon** [comment]
I'm not sure how to do that, but if it works for you, it's fine, thanks a lot!

**Comment by eleftherioszisis** [comment]
The cell loads fine with the change @mgeplf .
