### ISSUE TITLE
Dead link to Glia H5 specificiation

### ISSUE THREAD

**Issue by DexterAntonio** [BlueBrain/MorphIO#423]
Hi, 

Thank you for maintaining this package! 

I have some segmented microglia masks that I am attempting to turn into MorphIO GliaCell morphologies. In the documentation, [this page](https://morphio.readthedocs.io/en/latest/glia.html) is devoted to describing the format of glia cells. The page provides a dead link to an h5 specification for the glia cells and provides no other additional information. 

I tried finding that specification with Google, but I was not successful. Can you please point me to that specification and any additional resources involving using MorphIO and NeuroM with microglia masks? 

Thank You,
Dexter

**Comment by mgeplf** [comment]
It should be available at: https://morphology-documentation.readthedocs.io/en/latest/h5v1.html

I will update the links in the repos - thanks!

**Comment by mgeplf** [comment]
The documentation will only be updated officially when a  release is made; hope the above link works for you in the meantime @DexterAntonio.

Thanks for the issue.
