### ISSUE TITLE
Drop `-Werror` from compiler flags

### ISSUE THREAD

**Issue by 1uc** [BlueBrain/MorphIO#426]
Please consider dropping `-Werror` from the compiler flags. Today it's not possible to install `morphio` on ArchLinux which has updated GCC to 12.2.0. It seems this version of the compiler has introduced new diagnostics which are emitted when building `morphio`. As a result I can't install any packages that have `morphio` as a dependency. Unless I install a different compiler.

Suggestions:
* Simply drop `-Werror`; and keep fixing warning as one notices them during regular development cycles.
* Add a flag `MORPHIO_WITH_WERROR` (or similar) which defaults to `Off`. During CI, for selected compilers one could set the flag to `On` to check that `morphio` actually builds without warnings on those selected compilers.
* Add the same flags with default `Off` allowing us to disable `-Werror` when building with say Spack.

**Comment by mgeplf** [comment]
Yup, fully agree, not sure when I'll have a moment to give this a fix; I'm tempted to turn it on automatically for `Debug` builds, like we do in libsonata.

**Comment by mgeplf** [comment]
what happens if you set `-DMorphIO_CXX_WARNINGS=OFF`: https://github.com/BlueBrain/MorphIO/blob/master/CMakeLists.txt#L9

**Comment by 1uc** [comment]
Seems to work. I'll update the Spack recipe accordingly. Thank you!
