### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by matz-e** [BlueBrain/MorphIO#429]
There have been a few improvements living on `master` that would be *very* nice to have in a release, especially #392, #389. Could we please push a 3.3.4?

**Comment by eleftherioszisis** [comment]
It's fine by me after fixing the failing tests with #430

**Comment by Helveg** [comment]
Could Python 3.10 and 3.11 wheels be built in this release as well?

**Comment by eleftherioszisis** [comment]
@Helveg, MorphIO already releases wheels for 3.10.

3.11 wheels will be included as soon as h5py includes wheels for 3.11:
https://pypi.org/project/h5py/#files

**Comment by mgeplf** [comment]
Sorry, we're still behind on this - we should do it soon.

**Comment by mgeplf** [comment]
Ok, I'm working on this today; I need to see if linux/mac 3.11 wheels build properly.

Unfortunately, since h5py isn't building 3.11 wheels for windows, I will have to skip that platform for now.

**Comment by mgeplf** [comment]
Seems like azure/github actions are having an outage:
https://github.com/BlueBrain/MorphIO/actions/runs/3881673097/jobs/6620943353

I'll circle back in a bit.

**Comment by mgeplf** [comment]
seems we have CI again; I will do this today.

**Comment by mgeplf** [comment]
I apologize for the long delay, but we've made a release:
https://github.com/BlueBrain/MorphIO/releases/tag/v3.3.4
