### ISSUE TITLE
Relicense MorphIO from LGPL 3.0 to Apache-2.0 

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/MorphIO#455]
### Summary

We would like to change the license for MorphIO from the current LGPL to [Apache License, version 2.0](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)).

### Why Apache-2.0?

The motivation for this license change is maximize the accessibility of MorphIO and integration into open source software without doubts around license compatibility (e.g. integration at source level in BSD/Apache/MIT projects). By being more open/flexible with the license, we believe it will be helpful in longer term.

### What do contributors need to do?

We would like to ask permission from all **external/non-bbp contributors** to change the license to Apache 2.0. As far as I see, the external contributors are: 

- [x] @ptoharia 
- [x]  @Helveg 
- [x] @musicinmybrain.

If you agree with the proposed license change, we would like to request you to copy the message below, fill in the blanks and paste it into this issue.

```
My name is _________________________, and I am a contributor to MorphIO
with GitHub username _________________________.

I consent to change the current license contained in the License file at
https://github.com/BlueBrain/MorphIO/blob/master/COPYING from the
LGPL-3 license to the Apache License 2.0 with respect to all of my
contributions.
```

If you have any questions or concerns, please ask here or send an email to me/us.

Thanks!

**Comment by Helveg** [comment]
My name is Robin De Schepper, and I am a contributor to MorphIO
with GitHub username Helveg.

I consent to change the current license contained in the License file at
https://github.com/BlueBrain/MorphIO/blob/master/COPYING from the
LGPL-3 license to the Apache License 2.0 with respect to all of my
contributions.

**Comment by pramodk** [comment]
@musicinmybrain and @ptoharia: if you have time, could you take a look at the above message? thank you very much in advance!

**Comment by musicinmybrain** [comment]
My name is Benjamin Alan Beasley, and I am a contributor to MorphIO
with GitHub username musicinmybrain.

I consent to change the current license contained in the License file at
https://github.com/BlueBrain/MorphIO/blob/master/COPYING from the
LGPL-3 license to the Apache License 2.0 with respect to all of my
contributions.

**Comment by ptoharia** [comment]
My name is Pablo Toharia, and I am a contributor to MorphIO
with GitHub username ptoharia.

I consent to change the current license contained in the License file at
https://github.com/BlueBrain/MorphIO/blob/master/COPYING from the
LGPL-3 license to the Apache License 2.0 with respect to all of my
contributions.

**Comment by mgeplf** [comment]
This is completed in #467; thanks everyone for your help and responsiveness - it is greatly appreciated.  Thanks to @pramodk for leading this.
