### ISSUE TITLE
How to create a morphology with mut and SomaType.SOMA_NEUROMORPHO_THREE_POINT_CYLINDERS ?

### ISSUE THREAD

**Issue by arnaudon** [BlueBrain/MorphIO#480]
I am trying to create a simple morphology with a 3 points soma with morphio, but it seems to not give the correct parent id assignment for the 3rd point. It should be to id 1, but it is on id 2.

**Comment by jdcourcol** [comment]
Just to put more context:
Alexis is able to create such a morphology:
<img width="635" alt="image" src="https://github.com/BlueBrain/MorphIO/assets/5441880/d196a9ca-751f-48f8-8474-f1ee4e5996f6">

However, it is not compliant to the spec:
" The second and third soma points, as well as all starting points (roots) of dendritic and axonal arbors have this first point as the parent (parent ID 1)."
from this page: https://neuromorpho.org/SomaFormat.html
referenced by morph-io: https://morphio.readthedocs.io/en/latest/specification.html#id2 for 3 points soma.

**Comment by mgeplf** [comment]
@arnaudon: can you make a snippet of what you are doing, so I can have a look?

The soma formats are constantly a headache because when they have 3 points, they can either be a *proper* (IMO) set of 2 stacked cylinders, *OR* the 3 point soma from neuromorpho.

Clearly, this needs to be cleaned up, regardless.

**Comment by arnaudon** [comment]
Yes, I noticed, I want to make a 3 point some as in neuromorpho. But probably the best is just to save a str directly, instead of creating a morphio object and somehow tell morphio it should be a 3 point neuromorpho thing

**Comment by arnaudon** [comment]
@jdcourcol , in fact, why do we want placeholder morph to be neuromorpho 3 points, and not 2 cylinder version?

**Comment by mgeplf** [comment]
>  in fact, why do we want placeholder morph to be neuromorpho 3 points, and not 2 cylinder version?

What about a single point; then it's just a sphere that has the nice property that its surface area is the same as a cylinder (not including the endcaps)

**Comment by jdcourcol** [comment]
>@jdcourcol , in fact, why do we want placeholder morph to be neuromorpho 3 points, and not 2 cylinder version?

We don't want that: this is what the cell team provided to us. I want the format to be correct. Then if it a 2 cylinders soma, I am fine with it too.

**Comment by arnaudon** [comment]
ok, so the morph created here is a valid one with 2 cylinders, not a neuromorpho 3 points, right? https://github.com/BlueBrain/BluePyEModel/blob/main/bluepyemodel/tools/morphology.py
