### ISSUE TITLE
Make three point soma warning more clear

### ISSUE THREAD

**Issue by arnaudon** [BlueBrain/MorphIO#491]
This throws some warnings, without mention of three points soma, so it is un-understandable from a user not familiar with the internals of the code: https://github.com/BlueBrain/MorphIO/blob/54ffbd9fb01c16c9ccc8e57d4dc28f152a2962b4/src/shared_utils.cpp#L128 
I would be useful to mention three point soma in the warning, or something like that.

**Comment by mgeplf** [comment]
Yup, I agree, thanks.
