### ISSUE TITLE
No whl file that works with Python 3.13

### ISSUE THREAD

**Issue by Christian-B** [BlueBrain/MorphIO#502]
We use github action to test our code.

https://github.com/SpiNNakerManchester/sPyNNaker

We install Morphio via https://github.com/NeuralEnsemble/PyNN

When testing with python 3.12 (or lower)
It reports
Downloading morphio-3.3.9-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (3.5 kB)
and all works

When testing with python 3.13 (yes I know this is still in pre release)
it reports
Downloading morphio-3.3.9.tar.gz (600 kB)
And then fails to build.

Full error stack available if requested.

**Comment by mgeplf** [comment]
Hello,
Sorry about the slow reply; we'll be turning on Python 3.13 when it's officially released.
Unfortunately, we don't have the time to set it up at the moment.

**Comment by Christian-B** [comment]
Thank you for the new release!

We are now able to install with Python 3.13

OK to close.

**Comment by mgeplf** [comment]
You're welcome!
