### ISSUE TITLE
Raise warning if multiple section types within a section

### ISSUE THREAD

**Issue by ssssarah** [BlueBrain/MorphIO#503]
Example: 
https://bbp.epfl.ch/nexus/web/bbp-external/seu/resources/https:%2F%2Fbbp.epfl.ch%2Fdata%2Fbbp-external%2Fseu%2Fe7b9b6e9-9dc3-4831-91fa-34cb45a5758c

See [BBPP134-1412](https://bbpteam.epfl.ch/project/issues/browse/BBPP134-1412)

**Comment by mgeplf** [comment]
It's easy enough to add this; however I wonder if it's actually a warning we should emit at the morphIO level: the file can still be parsed, and that's what's in the file.  It's possible to check at "higher" levels of software if this exists.

I'm still not convinced that MorphIO is the place to make judgements about what is physiologically possible, versus what is file-format possible.

**Comment by ssssarah** [comment]
I understand what you mean. Do you think a morpho_check in neurom would be more appropriate?

**Comment by mgeplf** [comment]
Good point, that may be the place for it.
I think I might need to stop putting off the merging the enhanced SWC reader, because the current one may trip on section changes, though.

I will check shortly.

**Comment by mgeplf** [comment]
When I said `Good point, that may be the place for it.` it was in reply to maybe `morph_check` is the place for it.

> If it doesn't, then I would think the check rightfully lives here?
Yup, agreed.

**Comment by mgeplf** [comment]
what do you think @eleftherioszisis?

Since it's allowed in the SWC spec, I think it should be allowed here as well.
It's a matter of thinking where to put a check for things that aren't biologically sane: do we put it in neurom, or one of the other morph tools?

**Comment by mgeplf** [comment]
(FYI, I did the change yesterday on the updated parser: https://github.com/BlueBrain/MorphIO/tree/section-change-error)

**Comment by eleftherioszisis** [comment]
Given that we expect all representations (HDF5, ASCII, SWC) to have non-changing types within a section, it makes sense to emit a warning if this expectation is not met for SWC, which iirc is the only format that allows the types on the point leve.

**Comment by mgeplf** [comment]
Oops, missed this.
Hmm, interesting thought.
I'm not sure that emitting warnings on read are required for all mismatches in the underlying formats.
However, when *writing* a file, if the format doesn't allow a certain construct, there should be a hard error.

@eleftherioszisis any thoughts on where a check like this could go, if it wasn't implemented in MorphIO?

**Comment by mgeplf** [comment]
The behavior about splitting a section when the type changes was also discussed here:
https://github.com/BlueBrain/MorphIO/issues/469

I suppose if we need to emit a warning, that is fine - since otherwise one wouldn't know that this behavior happened.
Time to get this new parser merged, I think is the main point.

**Comment by mgeplf** [comment]
After the discussions with @eleftherioszisis, I have implemented what we thought the best tradeoff is: https://github.com/BlueBrain/MorphIO/pull/504

In default operation, a section type change without a branching point results in an exception being raised.
This keeps the section definition correct with what MorphIO has always said: that a section is defined as existing between two branching points.
An additional loading option is added `unifurcated_section_change` which will create new sections when the type changes, but add a warning when that happens.

@ssssarah if you want to try it out, the wheels are available as artifacts here:
https://github.com/BlueBrain/MorphIO/actions/runs/11180055954

**Comment by mgeplf** [comment]
This should be fixed by: https://github.com/BlueBrain/MorphIO/pull/510

I'm going to close this, feel free to reopen if there is an issue.
