### ISSUE TITLE
Use `size_t` instead of `uint32_t`

### ISSUE THREAD

**Issue by eleftherioszisis** [BlueBrain/MorphIO#65]
I was wondering if it would be preferable to use the more general and less constraining `size_t` where `unsinged int` is explicitly used as a type (mainly ids).

I don't see any reason in constraining the implementation to 32 bit ints. Thoughts?

**Comment by mgeplf** [comment]
I think it's an efficiency thing: at the moment, I don't think it's expected to have morphologies with more than 4 billion sections, so using more storage isn't necessary.  However, it's likely that people will have many morphologies in memory at the same time, at which using the large size becomes an issue.

Do you expect to have IDs larger than 4e9?

**Comment by eleftherioszisis** [comment]
Yes, it could be the case for the vasculature morphology, which can have ridiculous sizes.

**Comment by eleftherioszisis** [comment]
Also in 64 bit architectures 32 bit types are not well aligned right? Thus, it would be more efficient to use 64bit types in that case, right?

**Comment by mgeplf** [comment]
> Yes, it could be the case for the vasculature morphology, which can have ridiculous sizes.

4 billion segments means that the hdf5 representation is on the order of 4e9 * 4 * 4 = 64 gigabytes.  Do we have those already?

> Also in 64 bit architectures 32 bit types are not well aligned right? Thus, it would be more efficient to use 64bit types in that case, right?

I wouldn't worry about this, but usually the alignment requirements are on 4 byte word boundaries (2 bytes in some cases), and the latest intel architectures are taking less of a penalty for violating this.

**Comment by eleftherioszisis** [comment]
> 4 billion segments means that the hdf5 representation is on the order of 4e9 * 4 * 4 = 64 gigabytes. Do we have those already?
> 
Nope, we don't have these datasets yet.
> 
> I wouldn't worry about this, but usually the alignment requirements are on 4 byte word boundaries (2 bytes in some cases), and the latest intel architectures are taking less of a penalty for violating this.

I see. OK, then we could keep it as it right now until the big datasets arrive.
