### ISSUE TITLE
Add LICENCE and ACKNOWLEDGMENT

### ISSUE THREAD

**Issue by wizmer** [BlueBrain/MorphIO#72]

**Comment by wizmer** [comment]
@alex4200 Do you have the text that should be put there for the both the licence and the acknowledgment ?
Thanks

**Comment by alex4200** [comment]
@wizmer Please see the updated [OS Guidelines](https://bbpteam.epfl.ch/project/spaces/display/QA/Open+Source+Standard+Checklist). This should contain the information for the LICENSE and ACKNOWLEDGMENT. If you cannot find it, or have questions, let me know.
