### ISSUE TITLE
Access to connectivity information without generating the sections (immutable)

### ISSUE THREAD

**Issue by eleftherioszisis** [BlueBrain/MorphIO#85]
My understanding for the immutable Morphology is that the section connectivity is stored in a table.

Currently, one can access the morphology points and properties, such as diameters, but there is not way to access the section connectivity from the morphology level.

The section connectivity could be returned in the form of an edge list e.g.
```python
from morphio import Morphology
morphology = Morphology(path)
section_connectivity = morphology.section_connectivity
```
which would return an array like the following:
```
[[0, 1], [1, 2], [1, 3]]
```

Expanding on this, given that the section has an associated id, then we could retrieve the specific section by id, while having the section node adjacency.

Returning also the point connectivity can be useful for graph analysis. For example:
```python
from morphio import Morphology
morphology = Morphology(path)
points = morphology.points
point_connectivity = morphology.point_connectivity
```
This would allow to directly convert the morphology point connectivity into an adjacency matrix of the vertices / points.

**Comment by arnaudon** [comment]
Yes, that would be really nice to have. I'm interested in this from a 'math' perspective of understanding the morphological properties/features of neurons.

I think that a good option could be the following:
return a .csv file (or something like that), where each line has the following:
- id_a: id of the point nearest to soma
- id_b: id of the other point forming the segment
- lengths: lengths of the segment
- radius: mean (?) radius or radius_a/radius_b...
- other meaningful attributes of segments... 

In addition, if there are any interesting point attributes, we could return another .csv, with a list of points, there id corresponding to the ids in the segment list, and their attributes. 

Thanks!
