### ISSUE TITLE
Unable to pip install MorphIO in Mac OSX

### ISSUE THREAD

**Issue by eleftherioszisis** [BlueBrain/MorphIO#98]
It seems that there is a platform specific compilation issue when MorphIO is compiled in Mac OSX. Currently there is no workaround because there is no wheel for mac osx.

I tried:
```pip install morphio --user```

Compilation output:
[morphio_install_error.txt](https://github.com/BlueBrain/MorphIO/files/3566417/morphio_install_error.txt)

Thanks

**Comment by wizmer** [comment]
Fixed in https://github.com/BlueBrain/MorphIO/commit/7c73cd6c68a4fa38b67de69432f645330133dc07
